const PROVIDER_PRESETS = [
  { id: 'aliyun-bailian', name: '阿里云百炼 (DashScope)', apiType: 'openai', url: 'https://dashscope.aliyuncs.com/compatible-mode/v1', endpoint: '/chat/completions', website: 'https://dashscope.aliyun.com/' },
  { id: 'zhipu-glm-official', name: '智谱 GLM (官方)', apiType: 'openai', url: 'https://open.bigmodel.cn/api/paas/v4', endpoint: '/chat/completions', website: 'https://open.bigmodel.cn/' },
  { id: 'kimi-moonshot', name: '月之暗面 Kimi (Moonshot)', apiType: 'openai', url: 'https://api.moonshot.cn/v1', endpoint: '/chat/completions', website: 'https://platform.moonshot.cn/' },
  { id: 'deepseek-official', name: 'DeepSeek (官方)', apiType: 'openai', url: 'https://api.deepseek.com/v1', endpoint: '/chat/completions', website: 'https://platform.deepseek.com/' },
  { id: 'stepfun-official', name: '阶跃星辰 StepFun (官方)', apiType: 'openai', url: 'https://api.stepfun.com/v1', endpoint: '/chat/completions', website: 'https://platform.stepfun.com/' },
  { id: 'siliconflow-official', name: '硅基流动 SiliconFlow (官方)', apiType: 'openai', url: 'https://api.siliconflow.cn/v1', endpoint: '/chat/completions', website: 'https://siliconflow.cn/' },
  { id: 'modelscope-official', name: '魔搭 ModelScope (官方)', apiType: 'openai', url: 'https://api-inference.modelscope.cn/v1', endpoint: '/chat/completions', website: 'https://modelscope.cn/' },
  { id: 'volcengine-ark', name: '火山引擎方舟 Ark', apiType: 'openai', url: 'https://ark.cn-beijing.volces.com/api/v3', endpoint: '/chat/completions', website: 'https://console.volcengine.com/ark' },
  { id: 'baidu-qianfan', name: '百度智能云千帆', apiType: 'openai', url: 'https://qianfan.baidubce.com/v2', endpoint: '/chat/completions', website: 'https://cloud.baidu.com/product/wenxinworkshop' },
  { id: 'lingyi-yi', name: '零一万物 Yi', apiType: 'openai', url: 'https://api.lingyiwanwu.com/v1', endpoint: '/chat/completions', website: 'https://platform.lingyiwanwu.com/' },
  { id: 'baichuan-ai', name: '百川智能 Baichuan', apiType: 'openai', url: 'https://api.baichuan-ai.com/v1', endpoint: '/chat/completions', website: 'https://platform.baichuan-ai.com/' },

  { id: 'deepseek', name: 'DeepSeek', apiType: 'openai', url: 'https://api.deepseek.com/v1', endpoint: '/chat/completions', website: 'https://platform.deepseek.com/' },
  { id: 'zhipu-glm', name: 'Zhipu GLM', apiType: 'openai', url: 'https://open.bigmodel.cn/api/paas/v4', endpoint: '/chat/completions', website: 'https://open.bigmodel.cn/' },
  { id: 'zhipu-glm-en', name: 'Zhipu GLM en', apiType: 'openai', url: 'https://open.bigmodel.cn/api/paas/v4', endpoint: '/chat/completions', website: 'https://open.bigmodel.cn/' },
  { id: 'qwen-coder', name: 'Qwen Coder', apiType: 'openai', url: 'https://dashscope.aliyuncs.com/compatible-mode/v1', endpoint: '/chat/completions', website: 'https://dashscope.aliyun.com/' },
  { id: 'kimi-k2-5', name: 'Kimi k2.5', apiType: 'openai', url: 'https://api.moonshot.cn/v1', endpoint: '/chat/completions', website: 'https://platform.moonshot.cn/' },
  { id: 'kimi-for-coding', name: 'Kimi For Coding', apiType: 'openai', url: 'https://api.moonshot.cn/v1', endpoint: '/chat/completions', website: 'https://platform.moonshot.cn/' },
  { id: 'stepfun', name: 'StepFun', apiType: 'openai', url: 'https://api.stepfun.com/v1', endpoint: '/chat/completions', website: 'https://platform.stepfun.com/' },
  { id: 'minimax', name: 'MiniMax', apiType: 'openai', url: 'https://api.minimax.chat/v1', endpoint: '/chat/completions', website: 'https://www.minimaxi.com/' },
  { id: 'minimax-en', name: 'MiniMax en', apiType: 'openai', url: 'https://api.minimax.chat/v1', endpoint: '/chat/completions', website: 'https://www.minimaxi.com/' },
  { id: 'kat-coder', name: 'KAT-Coder', apiType: 'openai', url: '', endpoint: '/chat/completions', website: '' },
  { id: 'longcat', name: 'Longcat', apiType: 'openai', url: '', endpoint: '/chat/completions', website: '' },
  { id: 'doubaoseed', name: 'DouBaoSeed', apiType: 'openai', url: '', endpoint: '/chat/completions', website: '' },
  { id: 'bailing', name: 'BaiLing', apiType: 'openai', url: '', endpoint: '/chat/completions', website: '' },
  { id: 'xiaomi-mimo', name: 'Xiaomi MiMo', apiType: 'openai', url: '', endpoint: '/chat/completions', website: '' },
  { id: 'aihubmix', name: 'AiHubMix', apiType: 'openai', url: '', endpoint: '/chat/completions', website: '' },
  { id: 'dmxapi', name: 'DMXAPI', apiType: 'openai', url: 'https://www.dmxapi.cn/v1', endpoint: '/chat/completions', website: 'https://www.dmxapi.cn/' },
  { id: 'openrouter', name: 'OpenRouter', apiType: 'openai', url: 'https://openrouter.ai/api/v1', endpoint: '/chat/completions', website: 'https://openrouter.ai/' },
  { id: 'modelscope', name: 'ModelScope', apiType: 'openai', url: 'https://api-inference.modelscope.cn/v1', endpoint: '/chat/completions', website: 'https://modelscope.cn/' },
  { id: 'siliconflow', name: 'SiliconFlow', apiType: 'openai', url: 'https://api.siliconflow.cn/v1', endpoint: '/chat/completions', website: 'https://siliconflow.cn/' },
  { id: 'siliconflow-en', name: 'SiliconFlow en', apiType: 'openai', url: 'https://api.siliconflow.cn/v1', endpoint: '/chat/completions', website: 'https://siliconflow.cn/' },
  { id: 'novita-ai', name: 'Novita AI', apiType: 'openai', url: 'https://api.novita.ai/v3/openai', endpoint: '/chat/completions', website: 'https://novita.ai/' },
  { id: 'nvidia', name: 'Nvidia', apiType: 'openai', url: 'https://integrate.api.nvidia.com/v1', endpoint: '/chat/completions', website: 'https://build.nvidia.com/' },
  { id: 'youyunzhisuan', name: '优云智算', apiType: 'openai', url: '', endpoint: '/chat/completions', website: '' },
  { id: 'packycode', name: 'PackyCode', apiType: 'openai', url: '', endpoint: '/chat/completions', website: '' },
  { id: 'cubence', name: 'Cubence', apiType: 'openai', url: '', endpoint: '/chat/completions', website: '' },
  { id: 'aigocode', name: 'AIGoCode', apiType: 'openai', url: '', endpoint: '/chat/completions', website: '' },
  { id: 'rightcode', name: 'RightCode', apiType: 'openai', url: '', endpoint: '/chat/completions', website: '' },
  { id: 'aicodemirror', name: 'AICodeMirror', apiType: 'openai', url: '', endpoint: '/chat/completions', website: '' },
  { id: 'aicoding', name: 'AICoding', apiType: 'openai', url: '', endpoint: '/chat/completions', website: '' },
  { id: 'crazyrouter', name: 'CrazyRouter', apiType: 'openai', url: '', endpoint: '/chat/completions', website: '' },
  { id: 'sss-aicode', name: 'SSSAiCode', apiType: 'openai', url: '', endpoint: '/chat/completions', website: '' },
  { id: 'micu', name: 'Micu', apiType: 'openai', url: '', endpoint: '/chat/completions', website: '' },
  { id: 'ctok-ai', name: 'CTok.ai', apiType: 'openai', url: '', endpoint: '/chat/completions', website: '' },
  { id: 'aws-bedrock', name: 'AWS Bedrock', apiType: 'openai', url: '', endpoint: '/chat/completions', website: 'https://aws.amazon.com/bedrock/' }
]

function getProviderPresetById(id) {
  return PROVIDER_PRESETS.find(item => item.id === id) || null
}
